plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'eventee.server'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'eventee.server:common:0.0.1-SNAPSHOT'
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

repositories {
	maven {
		name = 'GitHubPackages'
		url = uri("https://maven.pkg.github.com/KTEventee/eventee-common")  // GitHub 리포지토리 URL
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("COMMON_USERNAME_GITHUB")
			password = project.findProperty("gpr.token") ?: System.getenv("COMMON_TOKEN_GITHUB")
		}
	}
}
